CREATE TABLE usuarios (id SERIAL PRIMARY KEY, nomeCompleto VARCHAR(50) NOT NULL,  
email VARCHAR(50) NOT NULL, nomeUsuario VARCHAR(20) NOT NULL, telefone VARCHAR(11) NOT NULL, 
	senha VARCHAR(100) NOT NULL);
